### ISSUE TITLE
Use it with c/c++

### ISSUE THREAD

**Issue by a-maza** [squeek502/resinator#9]
Hi,

I'm using zig to compile some C/C++ codebase. I'm wondering if it would be posible to use your tool to embed files in the final binary.

Do you have any example that I could use as a reference?

Thank you for your great tool

**Comment by squeek502** [comment]
If you're using a `build.zig`, see https://www.ryanliptak.com/blog/zig-is-a-windows-resource-compiler/#use-case-an-existing-c-program

If you're not, then you can use `zig rc` as a drop-in replacement for `rc.exe`: https://www.ryanliptak.com/blog/zig-is-a-windows-resource-compiler/#via-zig-rc

And if you're using an older version of Zig that doesn't have resinator built-in, then you'd need to compile standalone resinator (using a recent master version of Zig) and use that as your drop in `rc.exe` replacement: https://github.com/squeek502/resinator#compiling-resinator

**Comment by a-maza** [comment]
Hi squeek502,

Thank you for pointing out the tutorial. I managed to test it and get it running on WIndows. However, I want to be able to embed files also for linux aarch64. At the end, I think i will just probably use "xxd -i" to generate the header file and include it in my application for now.

Do you have any plan or idea how to extend resinator to work on linux systems?

Thanks

**Comment by squeek502** [comment]
I'm not sure exactly what you mean. If you mean you'd like to embed resources in non-PE/COFF executables, that isn't possible since the concept of embedded resources are specific to the PE/COFF format:

- https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#the-rsrc-section

**Comment by squeek502** [comment]
Closing, let me know if there's anything that's still not clear.
